name: CI PIPELINE

on:
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'
    run: pip install -r requirements.txt
    run: pip install flake8    
    run:
        flake8 app --count --select=E9,F63,F7,F82,F841 --show-source --statistics
        flake8 app --count --max-complexity=10 --max-line-length=127 --statistics
        flake8 tests --count --max-line-length=127 --statistics
  
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dependances
        run: pip install -r requirements.txt

      - name: Executer pytest avec couverture
        run: pytest tests/ -v --cov=src

  build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Recuperer le code
          uses: actions/checkout@v4

        - name: Installer Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            
        - name: Installer loutil de build
          run: pip install build

        - name: Generer le package Python
          run: python -m build

        - name: Upload du resultat comme artefact
          uses: actions/upload-artifact@v3
          with:
            name: mon-package-python
            path: dist/